// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3W_CZ6_Nt6KZ0F4Edi8MM7kHcmn2W-0E',
    appId: '1:57902038315:web:11520da1897369d977196e',
    messagingSenderId: '57902038315',
    projectId: 'guardia-app-ec59e',
    authDomain: 'guardia-app-ec59e.firebaseapp.com',
    storageBucket: 'guardia-app-ec59e.firebasestorage.app',
    measurementId: 'G-GWJR81CGB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4H1BvabtNUCHMdC7ysaoZuM8dgpKYza4',
    appId: '1:57902038315:android:d132662f344c0aa177196e',
    messagingSenderId: '57902038315',
    projectId: 'guardia-app-ec59e',
    storageBucket: 'guardia-app-ec59e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA0HDkR1fA9-n1E5g8fuVcuuaef59eip8',
    appId: '1:57902038315:ios:f0582510d521835b77196e',
    messagingSenderId: '57902038315',
    projectId: 'guardia-app-ec59e',
    storageBucket: 'guardia-app-ec59e.firebasestorage.app',
    iosBundleId: 'com.example.guardiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA0HDkR1fA9-n1E5g8fuVcuuaef59eip8',
    appId: '1:57902038315:ios:f0582510d521835b77196e',
    messagingSenderId: '57902038315',
    projectId: 'guardia-app-ec59e',
    storageBucket: 'guardia-app-ec59e.firebasestorage.app',
    iosBundleId: 'com.example.guardiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3W_CZ6_Nt6KZ0F4Edi8MM7kHcmn2W-0E',
    appId: '1:57902038315:web:be777d22d774cd2677196e',
    messagingSenderId: '57902038315',
    projectId: 'guardia-app-ec59e',
    authDomain: 'guardia-app-ec59e.firebaseapp.com',
    storageBucket: 'guardia-app-ec59e.firebasestorage.app',
    measurementId: 'G-TNLGBV6QRT',
  );
}
