name: guardia_app
description: "Guardia — Personal Safety & Community Security App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  # Dependency Injection
  get_it: any

  # Routing
  go_router: any

  # Network
  dio: ^5.9.2

  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: any
  geolocator: any
  geocoding: any

  # Firebase
  firebase_core: ^4.5.0
  firebase_auth: any
  firebase_messaging: any
  firebase_storage: any

  # Utilities
  intl: any
  json_annotation: any
  dartz: any

  # Notifications
  flutter_local_notifications: ^21.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: any
  json_serializable: any

  # Testing
  mockito: any
  bloc_test: any

  # Linting
  very_good_analysis: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/

