name: guardia_app
description: "Guardia — Personal Safety & Community Security App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dartz: any

  # Dependency Injection
  get_it: ^9.2.1

  # Routing
  go_router: ^17.1.0

  # Network
  dio: ^5.9.2

  # Maps & Location
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Firebase
  firebase_core: ^4.5.0
  firebase_auth: ^6.0.0
  firebase_messaging: ^16.1.2
  firebase_storage: ^13.0.0

  # Utilities
  intl: ^0.20.2
  json_annotation: ^4.9.0

  # Notifications/Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^21.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: any
  json_serializable: any

  # Testing
  mockito: any
  bloc_test: any

  # Linting
  very_good_analysis: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/


