name: guardia_app
description: "Guardia — Personal Safety & Community Security App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: any
  equatable: any

  # Dependency Injection
  get_it: any

  # Routing
  go_router: any

  # Network
  dio: any

  # Maps & Location
  google_maps_flutter: any
  geolocator: any
  geocoding: any

  # Firebase
  firebase_core: any
  firebase_auth: any
  firebase_messaging: any
  firebase_storage: any

  # Utilities
  intl: any
  json_annotation: any

  # Notifications
  flutter_local_notifications: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: any
  json_serializable: any

  # Testing
  mockito: any
  bloc_test: any

  # Linting
  very_good_analysis: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/